FROM node:20-slim
# Install libatomic dan tools yang dibutuhkan sharp/baileys jika diperlukan
RUN apt-get update && apt-get install -y libatomic1 ffmpeg webp && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
CMD ["node", "index.js"]